"""initial market data schema

Revision ID: 12d9e996cafd
Revises: 
Create Date: 2026-05-18 21:23:17.336939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d9e996cafd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('isin', sa.Text(), nullable=True),
    sa.Column('figi', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('canonical_id'),
    sa.UniqueConstraint('figi'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('company_provider_xref',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_ticker', sa.Text(), nullable=False),
    sa.Column('provider_name', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['companies.canonical_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_ticker')
    )
    op.create_table('financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('gross_profit', sa.Numeric(), nullable=True),
    sa.Column('operating_income', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('ebitda', sa.Numeric(), nullable=True),
    sa.Column('cash', sa.Numeric(), nullable=True),
    sa.Column('total_debt', sa.Numeric(), nullable=True),
    sa.Column('net_debt', sa.Numeric(), nullable=True),
    sa.Column('total_equity', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('capex', sa.Numeric(), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(), nullable=True),
    sa.Column('price_to_book', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('sources', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['companies.canonical_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'period')
    )
    op.create_table('quotes',
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['companies.canonical_id'], ),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_table('raw_financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['companies.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['companies.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_quotes')
    op.drop_table('raw_financials')
    op.drop_table('quotes')
    op.drop_table('financials')
    op.drop_table('company_provider_xref')
    op.drop_table('companies')
    # ### end Alembic commands ###
